##### create array

In [11]:
import numpy as np

In [12]:
x= np.array([25,44,89,56])


In [13]:
print(x)

[25 44 89 56]


In [14]:
type(x)

numpy.ndarray

In [15]:
x.ndim

1

In [16]:
x

array([25, 44, 89, 56])

In [17]:
x.dtype

dtype('int32')

In [19]:
x= np.array([25,44,89,56],dtype=np.int8)


In [20]:
x

array([25, 44, 89, 56], dtype=int8)

In [27]:
x[0]= 100

In [23]:
x= np.array([25,44,89,56],dtype=np.uint8)


In [24]:
x

array([25, 44, 89, 56], dtype=uint8)

In [26]:
x[0]=40

In [28]:
x.size

4

In [29]:
x.shape

(4,)

In [31]:
x.min()

44

In [32]:
x.max()

100

In [33]:
x

array([100,  44,  89,  56], dtype=uint8)

In [35]:
x.mean()

72.25

In [36]:
x.sort()

In [37]:
x.std()


22.982330169066845

In [38]:
x.sum()

289

In [42]:
y=np.array([45,34.5,56,67])

In [40]:
type(y)

numpy.ndarray

In [43]:
y

array([45. , 34.5, 56. , 67. ])

In [44]:
y.dtype

dtype('float64')

In [45]:
z=np.array([45,34.5,56,67,True])

In [46]:
z

array([45. , 34.5, 56. , 67. ,  1. ])

In [47]:
z=np.zeros(10)

In [48]:
z


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
q=np.ones(10)

In [50]:
q


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
q=np.ones(10)

In [57]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [58]:
np.arange(4,10,2)

array([4, 6, 8])

##### arrray operation

In [59]:
num1=np.array([34,35,67,88,34])
num2=np.array([34,67,23,90,23])

In [60]:
num1+10

array([44, 45, 77, 98, 44])

In [62]:
num1 /2


array([17. , 17.5, 33.5, 44. , 17. ])

In [63]:
num1+num2

array([ 68, 102,  90, 178,  57])

In [64]:
[35,55,7,8]*3

[35, 55, 7, 8, 35, 55, 7, 8, 35, 55, 7, 8]

##### matrix

In [69]:
M=np.array([[2,3,4],[3,5,4]])

In [70]:
M


array([[2, 3, 4],
       [3, 5, 4]])

In [71]:
M.dtype

dtype('int32')

In [73]:
M.size

6

In [74]:
M.ndim

2

In [76]:
M[1][1]


5

In [77]:
M

array([[2, 3, 4],
       [3, 5, 4]])

In [80]:
M[1:1,1:1]

array([], shape=(0, 0), dtype=int32)

In [81]:
M=np.array([[2,3,4],[3,5,4],[3,5,8],[3,2,9]])

In [82]:
M


array([[2, 3, 4],
       [3, 5, 4],
       [3, 5, 8],
       [3, 2, 9]])

In [93]:
M1=M.reshape(4,3)


In [94]:
M1

array([[2, 3, 4],
       [3, 5, 4],
       [3, 5, 8],
       [3, 2, 9]])

M=np.array([[2,3,4],[3,5,4],[3,5,8],[3,2,9]])

In [108]:
M=np.array([[2,3,4],[3,5,4],[3,5,8],[3,2,9]])
M

array([[2, 3, 4],
       [3, 5, 4],
       [3, 5, 8],
       [3, 2, 9]])

In [109]:
M.reshape(2,-1)

array([[2, 3, 4, 3, 5, 4],
       [3, 5, 8, 3, 2, 9]])

In [110]:
M.reshape(-1)

array([2, 3, 4, 3, 5, 4, 3, 5, 8, 3, 2, 9])

In [111]:
M.size

12

In [112]:
M.T

array([[2, 3, 3, 3],
       [3, 5, 5, 2],
       [4, 4, 8, 9]])

In [103]:
M.min()

2

In [106]:
M.min(axis=1)

array([2, 3, 3, 2])

In [107]:
M.sum(axis=0)

array([11, 15, 25])

In [115]:
y.argmax()

3

In [116]:
y

array([45. , 34.5, 56. , 67. ])

In [117]:
M.dtype

dtype('int32')

In [118]:
M=M.astype(np.float16)

In [119]:
M.dtype


dtype('float16')

In [120]:
M

array([[2., 3., 4.],
       [3., 5., 4.],
       [3., 5., 8.],
       [3., 2., 9.]], dtype=float16)

In [122]:
x


array([ 44,  56,  89, 100], dtype=uint8)

In [123]:
y=x

In [124]:
y[0]=2

In [125]:
x

array([  2,  56,  89, 100], dtype=uint8)

In [126]:
id(y)

1561468376848

In [127]:
id(x)

1561468376848

In [128]:
y=x.copy()
y

array([  2,  56,  89, 100], dtype=uint8)

In [129]:
id(y)

1561469489424